[bundle]
key = "culture.releases"
name = "Culture Releases"

[include]
source_patterns = [
  "films.us.wikipedia.*",
  "games.wikipedia.*",
  "anime.wikipedia.*",
  "television.us.wikipedia.*",
  "television.gb.wikipedia.*",
  "books.wikipedia.*",
]

[publish]
file_name_template = "culture-releases-{{year}}.ics"
